### PR TITLE
Issue 292 New Nav Link

### PR DESCRIPTION
**Pull request by beamalsky**

### CODE REVIEW

**Comment by derekeder** [comment]
Since the last 2 links are external, I'd recommend we collapse them into a dropdown as described in https://github.com/datamade/la-metro-councilmatic/issues/292#issuecomment-383705296

**Comment by beamalsky** [comment]
On it!

**Comment by beamalsky** [comment]
Dropdown is working, waiting for the go-ahead on titles.

**Comment by beamalsky** [comment]
@hancush if this looks good by you I think it's ready to merge.

**Pull request merged**
