### PR TITLE
Don't return future events as last action dates

### PR DESCRIPTION
**Pull request by hancush**

### CODE REVIEW

**Comment by hancush** [comment]
@reginafcompton should this have a test?

**Comment by reginafcompton** [comment]
A test would be much appreciated! [(Here, methinks.)](https://github.com/datamade/la-metro-councilmatic/blob/master/tests/test_bills.py)

Do you want me to pick this up, or do want to do the testing?

Thanks, @hancush !

**Comment by hancush** [comment]
i can do it, @reginafcompton!

**Comment by hancush** [comment]
@reginafcompton tell me about it!!! those docs sure pay dividends! ^_^

**Pull request merged**
