### PR TITLE
Put jetty config under version control

### PR DESCRIPTION
**Pull request by reginafcompton**
Another step for this issue: https://github.com/datamade/django-councilmatic/issues/157

@evz, I did this for deployment. Do you think it's okay to restart jetty with every Metro deployment? It seems like that could cause unwanted blips. 

```
mv -f $APP_PATH/configs/jetty.conf /etc/default/jetty
chown root.root /etc/default/jetty
service jetty restart
```

### CODE REVIEW

**Comment by evz** [comment]
Yeah let's see if there's an option to just reload the config without restarting.

**Comment by reginafcompton** [comment]
@evz - in the Upstart file I only see options for: start, stop, restart, supervise, run|demo, and check (which just "echos" the various config arguments). What do you think about requiring a manual restart for this step? (I cannot imagine needing to adjust jetty configurations very often.)

**Comment by evz** [comment]
Ooo, hey why don't we try this: https://wiki.apache.org/solr/CoreAdmin#RELOAD

As part of the deployment, just visit that URL using curl or something.

**Comment by reginafcompton** [comment]
@evz - this loads a new schema file for Solr 4, so we should implement this as part of the deployment...but does it reload Jetty configuration?

**Comment by evz** [comment]
Nope. I suppose if we want to do that, we'll want to do a manual restart. Changes like that seem a bit more fundamental.

**Comment by reginafcompton** [comment]
New deployment pattern:

```
# Move jetty config files to correct place
mv -f $APP_PATH/configs/jetty.conf /etc/default/jetty
chown root.root /etc/default/jetty

# Reload nginx and supervisor files, so it recognizes updated configs
service nginx reload
supervisorctl update 

# Move solr schema to correct place and reload
cp $APP_PATH/solr_scripts/schema.xml /opt/solr/multicore/$SOLR_CORE/conf/
wget "http://localhost:8983/solr/admin/cores?action=RELOAD&core=$SOLR_CORE"
```

**Pull request merged**
